### ISSUE TITLE
TP 5 Question 4

### ISSUE THREAD

**Issue by elisabethumblet** [BEAMS-EE/ELECH305#18]
Dans l'expression de S2, il y a, je crois, une erreur dans le premier terme du correctif : 

Il est écrit S2 = a1' b0 + a1' a0' b0 + a0' b1 b0, or c'est b1 qui vaut 1 dans le premier terme donc : S2 = a1' b1 + a1' a0' b0 + a0' b1 b0

**Comment by parastuffs** [comment]
C'est exact, merci beaucoup : )
