### ISSUE TITLE
[TP 6] Erreur question 1 f)

### ISSUE THREAD

**Issue by LucasPrieels** [BEAMS-EE/ELECH305#22]
La réponse a été donnée comme s'il n'y avait que 4 variables dans f alors qu'il y en a 5, si je ne me trompe pas la réponse avec 5 variables est
a'b'e', a'de', a'be, a'bd, a'c

**Comment by parastuffs** [comment]
Oui, ta version est correcte.
Je vais néanmoins corrigé l'énoncé pour retirer la variable `e`.
